;
CREATE USER IF NOT EXISTS "ADMIN" SALT '065bd2e3775aae9f' HASH 'd396304c26571e5edfe32d0106b946baee06cdcb51b79e2c6fa9e31332a3f6bf' ADMIN;
CREATE SEQUENCE IF NOT EXISTS "PUBLIC"."PRODUCT_SEQ" START WITH 1;
CREATE SEQUENCE IF NOT EXISTS "PUBLIC"."BASKET_SEQ" START WITH 1;
CREATE SEQUENCE IF NOT EXISTS "PUBLIC"."ADDRESS_SEQ" START WITH 1;
CREATE SEQUENCE IF NOT EXISTS "PUBLIC"."USERS_SEQ" START WITH 1;
CREATE SEQUENCE IF NOT EXISTS "PUBLIC"."USERCARD_SEQ" START WITH 1;
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."ADDRESS"(
    "ID" BIGINT NOT NULL,
    "BUILDING_NAME" VARCHAR(255),
    "FLOOR" VARCHAR(255),
    "HOUSE_NO" VARCHAR(255) NOT NULL,
    "KHET" VARCHAR(255),
    "KWANG" VARCHAR(255),
    "POST_CODE" INTEGER NOT NULL,
    "PROVINCE" VARCHAR(255),
    "ROAD" VARCHAR(255),
    "SOI" VARCHAR(255),
    "VILLAGE" VARCHAR(255),
    "PRIORITY" BIGINT,
    "USER_ID" BIGINT
);
ALTER TABLE "PUBLIC"."ADDRESS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ADDRESS;
CREATE CACHED TABLE "PUBLIC"."BASKET"(
    "ID" BIGINT NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "PRODUCT_ID" BIGINT,
    "USER_ID" BIGINT
);
ALTER TABLE "PUBLIC"."BASKET" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BASKET;
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."PRODUCT"(
    "ID" BIGINT NOT NULL,
    "DETAIL" VARCHAR(255),
    "NAME" VARCHAR(255),
    "PRICE_BAHT" DOUBLE,
    "QUANTITY" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT;
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."USER_CARD"(
    "ID" BIGINT NOT NULL,
    "CARD_NO" VARCHAR(255),
    "CARD_TYPE" VARCHAR(255),
    "CCV_OR_CVV" VARCHAR(255),
    "EXPIRE_MONTH" VARCHAR(255),
    "EXPIRE_YEAR" VARCHAR(255),
    "PRIORITY" BIGINT,
    "USER_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."USER_CARD" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_CARD;
CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."USER_INFO"(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "USERNAME" VARCHAR(255) NOT NULL
);
ALTER TABLE "PUBLIC"."USER_INFO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BC" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_INFO;
CREATE CACHED TABLE "PUBLIC"."TRANSACTION"(
    "ID" BIGINT NOT NULL,
    "GROUP_NUMBER" BIGINT,
    "AMOUNT" DOUBLE NOT NULL,
    "CREATED_DATE" TIMESTAMP,
    "ADDRESS_ID" BIGINT NOT NULL,
    "USER_CARD_ID" BIGINT NOT NULL,
    "PRODUCT_ID" BIGINT NOT NULL,
    "QUANTITY" BIGINT NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    "UPDATED_DATE" TIMESTAMP,
    "STATUS" VARCHAR(30)
);
ALTER TABLE "PUBLIC"."TRANSACTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TRANSACTION;
ALTER TABLE "PUBLIC"."USER_INFO" ADD CONSTRAINT "PUBLIC"."UK_F2KSD6H8HSJTD57IPFQ9MYR64" UNIQUE("USERNAME");
ALTER TABLE "PUBLIC"."ADDRESS" ADD CONSTRAINT "PUBLIC"."FKRQ48B9H2UVMJOSGJCCCQPDIFG" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER_INFO"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BASKET" ADD CONSTRAINT "PUBLIC"."FK5IQPIOSP63FVWD8PRQVKV3VEE" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER_INFO"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."USER_CARD" ADD CONSTRAINT "PUBLIC"."FKFRD3JCFOM3CAHVNUY18A2LLL3" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER_INFO"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BASKET" ADD CONSTRAINT "PUBLIC"."FKEKEW2GJLCCDP7HCLYYFP8S0L5" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."TRANSACTION" ADD CONSTRAINT "PUBLIC"."FKMSXB91NB6BEQC39K9U2AIIV3T" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER_INFO"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."TRANSACTION" ADD CONSTRAINT "PUBLIC"."FKECD3DPUR8G7YAGANUY93WWLOP" FOREIGN KEY("USER_CARD_ID") REFERENCES "PUBLIC"."USER_CARD"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."TRANSACTION" ADD CONSTRAINT "PUBLIC"."FKF7I7BDM0UQN31RWTVIQN7UUS7" FOREIGN KEY("ADDRESS_ID") REFERENCES "PUBLIC"."ADDRESS"("ID") NOCHECK;
